### ISSUE TITLE
Deployed relay fails with `Origin is not allowed by Access-Control-Allow-Origin`

### ISSUE THREAD

**Issue by troyschneringer** [smartlook/smartlook-relay-proxy#282]
**Describe the bug**
All calls to smartlook using the relay proxy fail with `Origin is not allowed by Access-Control-Allow-Origin`

**To Reproduce**
The relay is deployed to Google Cloud run via the following:
```
gcloud run deploy -q smartlook-relay \
    --image=smartlook/relay-proxy:latest \
    --cpu=1 --memory=256Mi \
    --platform=managed \
    --region=us-central1 \
    --allow-unauthenticated \
    --service-account=[IAM-SERVICE-ACCOUNT] \
    --port=8000
```

Domain mapping is setup and confirmed working with:
`curl https://smartlook.fons.com/recorder.js`

Smartlook is installed on the client using `smart look-client`:
```
import smartlook from "smartlook-client";
smartlook.init([KEY], { relayProxyUrl: "https://smartlook.fons.com/"  });
smartlook.record({ forms: true, emails: true, ips: true, numbers: true });
```

If `relayProxyUrl` is omitted, everything works fine.  However with `relayProxyUrl` set, recordings do not occur and networks calls to `https://smartlook.fons.com/manager/rec/sessions/0p4M-n8zDo_3tvI9uOq-s/active?projectKey=[KEY]` fail with a `500` and `Origin is not allowed by Access-Control-Allow-Origin`

**Expected behavior**
Successful calls to smartlook and recordings appear in the dashboard.

**Screenshots**
<img width="923" alt="Screenshot 2024-04-02 at 5 09 54 PM" src="https://github.com/smartlook/smartlook-relay-proxy/assets/1273031/3db6e2c4-201c-48ad-bb3b-f31d693d47e4">

**Comment by js-supp** [comment]
Can observe on https://next.fons.com/. @samialdury is this something with can help with?

**Comment by troyschneringer** [comment]
Turns out this was a GCP config issue.
A previous version of the proxy had been deployed with the US environment variables.  We when reverted to the defaults (by not setting the variables) Cloud Run did not clear out the old variable values causing a 500 error in the logs.
